worlds:
  Chillerlands:
  - adminboard
  - defaultscoreboard
  Chillerlands_the_end:
  - adminboard
  - endscoreboard
  Chillerlands_nether:
  - adminboard
  - netherscoreboard
permissions:
  adminboard: animatedscoreboard.admin
check_updates: true
