# 21 Aug 2012: Added logflushsecs
# 1 May  2013: Added wooddropscharcoal
# 16 May 2013: Added noburn(mob|player)by
# 13 Jun 2013: Added charcoaldrop node
# 22 SEp 2013: added lava place nodes
# 23 Nov 2013: Added speciesmax, variable charcoal accepting Material names.
# 17 Jan 2014: Added anydropchance, DARKOAK_LOG and ACACIA_LOG

nerf_fire:
  nodamageto:
    drops:
      fromfire: Chillerlands, Chillerlands_nether, Chillerlands_the_end
  wooddropscharcoal: Chillerlands, Chillerlands_nether, Chillerlands_the_end
  charcoaldrop:
    random: true
    max: 3
    speciesmax:
      JUNGLE_LOG: 0
      OAK_LOG: 2
      BIRCH_LOG: 1
      SPRUCE_LOG: 3
      ACACIA_LOG: 4
      DARKOAK_LOG: 5
    anydropchance: 75
  nostartby: {}
  logstart: {}
