Infinity Pick: false
Mob:
  AutoXP: true
  AutoPickup: true
AutoSmelt Compat Mode: false
Block AutoXP: true
Auto Chest: false
Full Inventory:
  Delete Item: false
  Warn: true
Gui:
  Contact Info: true
Allow BlockGui Permission: false
AutoBlock Quartz: false
