# RandomCoords: Need Help Setting Up? See the Wiki! https://github.com/jolbol1/RandomCoordinatesV2/wiki 
#  This will explain everything you need to know about all the options. 
#  Developed by Jolbol1
MaxCoordinate: 5000
MinCoordinate: 0
CooldownTime: 5
InvulTime: 10
TimeBeforeTeleport: 5
MaxAttempts: 20
RandomOrg: false
StopOnMove: true
StopOnCombat: true
ChunkLoader: false
Sound: ENTITY_ENDERDRAGON_FLAP
Effect: ENDER_SIGNAL
BannedWorlds:
- world_the_end
CheckingRadius: 100
Factions: false
GriefPrevention: false
AvoidPlayers: false
Towny: false
WorldBorder: false
WorldGuard: false
RedProtect: false
Kingdoms: false
VanillaBorder: true
SkyBlock: false
Residence: false
Regions:
- example
OnJoin: false
OnJoinCommand: none
BonusChest: false
BonusChestItems:
- WOOD_SWORD
Command: random
All: random
Others: random
Portals: random
Signs: random
Join: random
CommandCost: 0
PortalCost: 0
WarpCrossWorld: true
Limit: 0
LimiterApplys:
- Command
- Warps
TimeBeforeApplys:
- Command
- Warps
- Signs
CooldownApplys:
- Command
- Warps
Metrics: true
CircleRadiusDefault: false
CircleRadiusWorlds:
- example
debug: false
UpdateMessage: true
OnJoinWorlds:
- example
Experimental: true
